// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZsom3_hz7XqlD87F8QJKS7fwBj5wjRJI',
    appId: '1:1058538760131:web:f7265cbafcd50665fa3f76',
    messagingSenderId: '1058538760131',
    projectId: 'gron8839',
    authDomain: 'gron8839.firebaseapp.com',
    storageBucket: 'gron8839.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn4a78Psu75cPGO2s5OQUnhOC_UXsdIfQ',
    appId: '1:1058538760131:android:87c07c439b171129fa3f76',
    messagingSenderId: '1058538760131',
    projectId: 'gron8839',
    storageBucket: 'gron8839.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFF_5jxSZD01KR-io1iaMyeE4GKM_nPBE',
    appId: '1:1058538760131:ios:c1e0e5d66a63af1cfa3f76',
    messagingSenderId: '1058538760131',
    projectId: 'gron8839',
    storageBucket: 'gron8839.appspot.com',
    iosBundleId: 'com.example.gronk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFF_5jxSZD01KR-io1iaMyeE4GKM_nPBE',
    appId: '1:1058538760131:ios:c1e0e5d66a63af1cfa3f76',
    messagingSenderId: '1058538760131',
    projectId: 'gron8839',
    storageBucket: 'gron8839.appspot.com',
    iosBundleId: 'com.example.gronk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZsom3_hz7XqlD87F8QJKS7fwBj5wjRJI',
    appId: '1:1058538760131:web:2e816ea31faf7478fa3f76',
    messagingSenderId: '1058538760131',
    projectId: 'gron8839',
    authDomain: 'gron8839.firebaseapp.com',
    storageBucket: 'gron8839.appspot.com',
  );
}
